export default {
    name: "km",
    el: {
        breadcrumb: {
            label: "ផ្លូវ",
        },
        colorpicker: {
            confirm: "យល់ព្រម",
            clear: "លុប",
            defaultLabel: "ជ្រើសពណ៌",
            description: "ឧបករណ៍ជ្រើសពណ៌",
            alphaLabel: "កម្រិតថ្លា",
            alphaDescription: "កំណត់ភាពថ្លា",
            hueLabel: "ពណ៌",
            hueDescription: "កំណត់ពណ៌",
            svLabel: "តម្លៃពណ៌",
            svDescription: "កំណត់តម្លៃពណ៌",
            predefineDescription: "ពណ៌កំណត់ជាមុន",
        },
        datepicker: {
            now: "ឥឡូវនេះ",
            today: "ថ្ងៃនេះ",
            cancel: "បោះបង់",
            clear: "លុប",
            confirm: "យល់ព្រម",
            dateTablePrompt: "ប្រើព្រួញដើម្បីជ្រើសថ្ងៃ",
            monthTablePrompt: "ប្រើព្រួញដើម្បីជ្រើសខែ",
            yearTablePrompt: "ប្រើព្រួញដើម្បីជ្រើសឆ្នាំ",
            selectedDate: "ថ្ងៃដែលបានជ្រើស",
            selectDate: "ជ្រើសរើសថ្ងៃ",
            selectTime: "ជ្រើសរើសម៉ោង",
            startDate: "ថ្ងៃចាប់ផ្តើម",
            startTime: "ម៉ោងចាប់ផ្តើម",
            endDate: "ថ្ងៃបញ្ចប់",
            endTime: "ម៉ោងបញ្ចប់",
            prevYear: "ឆ្នាំមុន",
            nextYear: "ឆ្នាំក្រោយ",
            prevMonth: "ខែមុន",
            nextMonth: "ខែក្រោយ",
            year: "ឆ្នាំ",
            month1: "មករា",
            month2: "កុម្ភៈ",
            month3: "មីនា",
            month4: "មេសា",
            month5: "ឧសភា",
            month6: "មិថុនា",
            month7: "កក្កដា",
            month8: "សីហា",
            month9: "កញ្ញា",
            month10: "តុលា",
            month11: "វិច្ឆិកា",
            month12: "ធ្នូ",
            weeks: {
                sun: "អា",
                mon: "ច",
                tue: "អ",
                wed: "ពុ",
                thu: "ព្រ",
                fri: "សុ",
                sat: "ស",
            },
            weeksFull: {
                sun: "អាទិត្យ",
                mon: "ចន្ទ",
                tue: "អង្គារ",
                wed: "ពុធ",
                thu: "ព្រហស្បតិ៍",
                fri: "សុក្រ",
                sat: "សៅរ៍",
            },
            months: {
                jan: "មករា",
                feb: "កុម្ភៈ",
                mar: "មីនា",
                apr: "មេសា",
                may: "ឧសភា",
                jun: "មិថុនា",
                jul: "កក្កដា",
                aug: "សីហា",
                sep: "កញ្ញា",
                oct: "តុលា",
                nov: "វិច្ឆិកា",
                dec: "ធ្នូ",
            },
        },
        inputNumber: {
            decrease: "បន្ថយ",
            increase: "បន្ថែម",
        },
        select: {
            loading: "កំពុងផ្ទុក...",
            noMatch: "មិនមានលទ្ធផលត្រូវគ្នា",
            noData: "គ្មានទិន្នន័យ",
            placeholder: "សូមជ្រើសរើស",
        },
        mention: {
            loading: "កំពុងផ្ទុក...",
        },
        dropdown: {
            toggleDropdown: "បើក/បិទបញ្ជី",
        },
        cascader: {
            noMatch: "មិនមានលទ្ធផល",
            loading: "កំពុងផ្ទុក...",
            placeholder: "សូមជ្រើសរើស",
            noData: "គ្មានទិន្នន័យ",
        },
        pagination: {
            goto: "ទៅ",
            pagesize: "/ទំព័រ",
            total: "សរុប {total}",
            pageClassifier: "",
            page: "ទំព័រ",
            prev: "មុន",
            next: "បន្ទាប់",
            currentPage: "ទំព័របច្ចុប្បន្ន",
            prevPages: "ទំព័រមុន",
            nextPages: "ទំព័របន្ទាប់",
            deprecationWarning: "ព្រមាន៖ វិធីនេះនឹងត្រូវលុបនៅពេលក្រោយ",
        },
        dialog: {
            close: "បិទ",
        },
        drawer: {
            close: "បិទ",
        },
        messagebox: {
            title: "សារ",
            confirm: "យល់ព្រម",
            cancel: "បោះបង់",
            error: "មានកំហុស",
            close: "បិទ",
        },
        upload: {
            deleteTip: "ចុចលុបដើម្បីយកចេញ",
            delete: "លុប",
            preview: "មើលជាមុន",
            continue: "បន្ត",
        },
        slider: {
            defaultLabel: "ស្លាយ",
            defaultRangeStartLabel: "ចាប់ផ្តើម",
            defaultRangeEndLabel: "បញ្ចប់",
        },
        table: {
            emptyText: "គ្មានទិន្នន័យ",
            confirmFilter: "យល់ព្រម",
            resetFilter: "កំណត់ឡើងវិញ",
            clearFilter: "លុបតម្រង",
            sumText: "សរុប",
            selectAllLabel: "ជ្រើសទាំងអស់",
            selectRowLabel: "ជ្រើសជួរ",
            expandRowLabel: "ពង្រីក",
            collapseRowLabel: "បង្រួម",
            sortLabel: "តម្រៀប",
            filterLabel: "តម្រង",
        },
        tag: {
            close: "បិទ",
        },
        tour: {
            next: "បន្ទាប់",
            previous: "មុន",
            finish: "បញ្ចប់",
            close: "បិទ",
        },
        tree: {
            emptyText: "គ្មានទិន្នន័យ",
        },
        transfer: {
            noMatch: "មិនមានលទ្ធផល",
            noData: "គ្មានទិន្នន័យ",
            titles: ["បញ្ជីទី១", "បញ្ជីទី២"],
            filterPlaceholder: "ស្វែងរក",
            noCheckedFormat: "{total} ធាតុ",
            hasCheckedFormat: "បានជ្រើស {checked}/{total}",
        },
        image: {
            error: "បង្ហាញរូបភាពបរាជ័យ",
        },
        pageHeader: {
            title: "ត្រឡប់ក្រោយ",
        },
        popconfirm: {
            confirmButtonText: "យល់ព្រម",
            cancelButtonText: "បោះបង់",
        },
        carousel: {
            leftArrow: "មុន",
            rightArrow: "បន្ទាប់",
            indicator: "សូចនាករ",
        },
    },
};